openapi: 3.1.0
info:
  title: ai_tech_stack RAG Actions
  version: "1.0.0"
servers:
  - url: https://rag.keepbreath.ing
paths:
  /api/retrieve:
    post:
      operationId: retrieve
      summary: Retrieve top-k chunks for a query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [query]
              properties:
                query:
                  type: string
                  description: The user's search text
                top_k:
                  type: integer
                  minimum: 1
                  maximum: 20
                  default: 3
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  chunks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Chunk'
                required: [chunks]
components:
  schemas:
    Chunk:
      type: object
      required: [id, score, text]
      properties:
        id:
          type: string
        score:
          type: number
          format: float
        text:
          type: string
        source:
          type: string
          nullable: true
